use muebleria;
DELETE FROM PROVEEDORES (PVD_ID, PVD_NOMBRE, PVD_ITEMS, PVD_STOCK);
INSERT INTO USUARIOS (USU_ID, USU_NOMBRE, USU_APELLIDO, USU_EMAIL, USU_PASSWORD) VALUES ('39768585', 'Juan', 'Perez', 'juanperez@gmail.com', '123456');
INSERT INTO TIPOS_PRODUCTOS (TP_ID, TP_CATEGORIA, TP_MODELO) VALUES ('1', 'Sillón', 'Sillón de 2 plazas');
INSERT INTO PROVEEDORES (PVD_ID, PVD_NOMBRE, PVD_ITEMS, PVD_STOCK) VALUES ('1', 'Rodrigo Lopez', 'Sillón de 2 plazas', '20');
INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_PRECIO, PRO_TP_ID, PRO_PVD_ID) VALUES ('1', 'Sillón de 2 plazas', '80000', '1', '1');
INSERT INTO VENDEDORES (VND_ID, VND_NOMBRE, VND_APELLIDO) VALUES ('40123485', 'Lucas', 'Fernandez');
INSERT INTO VENTAS (VEN_ID, VEN_DATE, VEN_USU_ID, VEN_PRO_ID, VEN_VND_ID) VALUES ('1', '2022-06-17', '39768585', '1', '40123485');
